# Generated by Django 5.2.15 on 2026-06-07 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_patientportalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='administration_mode',
            field=models.CharField(choices=[('self_report', 'Self report'), ('interviewer_assisted', 'Interviewer assisted'), ('clinician_administered', 'Clinician administered')], default='self_report', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='administration_mode',
            field=models.CharField(choices=[('self_report', 'Self report'), ('interviewer_assisted', 'Interviewer assisted'), ('clinician_administered', 'Clinician administered')], default='self_report', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='source',
            field=models.CharField(choices=[('research_intake', 'Research intake'), ('patient_portal', 'Patient portal'), ('clinician_dashboard', 'Clinician dashboard'), ('admin', 'Admin')], default='patient_portal', max_length=32),
        ),
        migrations.CreateModel(
            name='BatteryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=16)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('administration_mode', models.CharField(choices=[('self_report', 'Self report'), ('interviewer_assisted', 'Interviewer assisted'), ('clinician_administered', 'Clinician administered')], default='self_report', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_assignments', to='clinical.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_assignments', to='clinical.assessmentsession')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='clinical.batteryassignment'),
        ),
        migrations.CreateModel(
            name='BatteryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batteryassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='clinical.batterytemplate'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('research', 'Research'), ('clinical_screening', 'Clinical screening'), ('data_reuse', 'Data reuse')], default='research', max_length=32)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clinical.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TabletAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_tokens', to='clinical.batteryassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryTemplateScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scale_id', models.CharField(max_length=64)),
                ('scale_label', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('role_visible_to', models.CharField(choices=[('patient', 'Patient'), ('research', 'Research'), ('clinician', 'Clinician'), ('all', 'All')], default='all', max_length=16)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='clinical.batterytemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'scale_id'), name='unique_template_scale')],
            },
        ),
    ]
