from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("auth/csrf/", views.csrf, name="csrf"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/me/", views.me, name="me"),
    path("patient/auth/login/", views.patient_login_view, name="patient_login"),
    path("patient/auth/token-login/", views.patient_token_login_view, name="patient_token_login"),
    path("patient/auth/logout/", views.patient_logout_view, name="patient_logout"),
    path("patient/auth/me/", views.patient_me, name="patient_me"),
    path("patient/assignments/", views.patient_assignments, name="patient_assignments"),
    path("patient/assignments/<int:assignment_id>/next/", views.patient_assignment_next, name="patient_assignment_next"),
    path("patient/assignments/<int:assignment_id>/results/", views.patient_assignment_results, name="patient_assignment_results"),
    path("research/templates/", views.research_templates, name="research_templates"),
    path("research/enroll/", views.research_enroll, name="research_enroll"),
    path("research/patients/", views.research_patients, name="research_patients"),
    path("research/patients/<int:patient_id>/assignments/", views.research_assign_patient, name="research_assign_patient"),
    path("research/assignments/<int:assignment_id>/tablet-token/", views.research_tablet_token, name="research_tablet_token"),
    path("research/assignments/<int:assignment_id>/progress/", views.research_assignment_progress, name="research_assignment_progress"),
    path("clinician/patients/", views.clinician_patients, name="clinician_patients"),
    path("clinician/patients/<int:patient_id>/profile/", views.clinician_patient_profile, name="clinician_patient_profile"),
    path("clinician/patients/<int:patient_id>/sessions/", views.clinician_patient_sessions, name="clinician_patient_sessions"),
    path("clinician/sessions/<uuid:session_id>/results/", views.clinician_session_result, name="clinician_session_result"),
    path("clinician/export/csv/", views.clinician_export_csv, name="clinician_export_csv"),
    path("patient/sessions/", views.patient_sessions, name="patient_sessions"),
    path("patient/sessions/<uuid:session_id>/results/", views.patient_results, name="patient_results"),
    path("patients/", views.patients, name="patients"),
    path("patients/<int:patient_id>/sessions/", views.sessions, name="sessions"),
    path("sessions/<uuid:session_id>/close/", views.close_session, name="close_session"),
    path("sessions/<uuid:session_id>/results/", views.results, name="results"),
    path("audit/", views.audit_logs, name="audit_logs"),
    path("backups/", views.backup_runs, name="backup_runs"),
    path("export/csv/", views.export_csv, name="export_csv"),
]
